// samples/svelte/src/lib/GameFooter.svelte
<!--
	QuantumTicTacToe is made by Rohan Pandit in 2017 and changed by Shouhei Uechi in 2021.
	  Copyright (C) 2021  Shouhei Uechi
	  Copyright (C) 2017  Rohan Pandit, available at <https://github.com/rohanp/QuantumTicTacToe/tree/master/>

	This file is part of QuantumTicTacToe.

	QuantumTicTacToe is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	QuantumTicTacToe is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with QuantumTicTacToe.  If not, see <https://www.gnu.org/licenses/>.
-->
<script lang="ts"></script>

<div class="game-footer">
	<p>
		<small>
			<a rel="license" href="https://www.gnu.org/licenses/">GNU Public Licensed</a>
		</small>
	</p>
	<p>
		<small>
			QuantumTicTacToe is written by Rohan Pandit in 2017 and changed by Shouhei Uechi in 2021.
		</small>
		<br />
		<small>
			Copyright &copy; 2021
			<a rel="author" href="https://github.com/u-sho">Shouhei Uechi</a>. Rights reserved.
		</small>
		<br />
		<small>
			Copyright &copy; 2017 Rohan Pandit, available at
			<a href="https://github.com/rohanp/QuantumTicTacToe/tree/master/">his GitHub repository</a>.
		</small>
	</p>
</div>

<style>
.game-footer {
	width: 100%;
	margin-top: 50px;
	text-align: center;
	background-color: var(--theme-color);
	color: white;
	& a {
		color: white;
		text-decoration-line: underline;
	}
}
</style>

// samples/vue/src/components/GameFooter.vue
<!--
   QuantumTicTacToe is made by Rohan Pandit in 2017 and changed by Shouhei Uechi in 2021.
     Copyright (C) 2021  Shouhei Uechi
     Copyright (C) 2017  Rohan Pandit, available at <https://github.com/rohanp/QuantumTicTacToe/tree/master/>

   This file is part of QuantumTicTacToe.

   QuantumTicTacToe is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   QuantumTicTacToe is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with QuantumTicTacToe.  If not, see <https://www.gnu.org/licenses/>.
-->
<template>
  <div class="game-footer">
    <p>
      <small>
        <a rel="license" href="https://www.gnu.org/licenses/">GNU Public Licensed</a>
      </small>
    </p>
    <p>
      <small>
        QuantumTicTacToe is written by Rohan Pandit in 2017 and changed by Shouhei Uechi in 2021.
      </small>
      <br />
      <small>
        Copyright &copy; 2021
        <a rel="author" href="https://github.com/u-sho">Shouhei Uechi</a>. Rights reserved.
      </small>
      <br />
      <small>
        Copyright &copy; 2017 Rohan Pandit, available at
        <a href="https://github.com/rohanp/QuantumTicTacToe/tree/master/">his GitHub repository</a>.
      </small>
    </p>
  </div>
</template>

<style>
.game-footer {
  width: 100%;
  margin-top: 50px;
  text-align: center;
  background-color: var(--theme-color);
  color: white;
  a {
     color: white;
     text-decoration-line: underline;
  }
}
</style>
